name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 设置 JDK 11
      - name: 设置 JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # 赋予 gradlew 脚本执行权限
      - name: 授权 gradlew 执行权限
        run: chmod +x showtaps/gradlew

      # 列出目录，调试用（可选）
      - name: 查看 showtaps 目录内容
        run: ls -l showtaps/

      # 编译项目
      - name: Gradle 编译
        run: ./showtaps/gradlew assembleDebug

      # 上传 APK 文件
      - name: 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: showtaps/app/build/outputs/apk/debug/*.apk
